dark_mode = false

[durations]
work_duration = 3300
break_duration = 300

[audio]
finish_sound = "assets/sounds/Mice_on_venus.mp3"

[todo]
database_file_path = "pocut/db/todo.sqlite"

[misc]
clock_type = true
